### PR TITLE
Postercard suggestion

### PR DESCRIPTION
**Pull request by iRobsc**
Here's a little suggestion on how the postercards could look instead. I also added a hover effect to it. :+1:

### CODE REVIEW

**Comment by iRobsc** [comment]
Wait something went wrong

**Comment by iRobsc** [comment]
I learned something about the git reverts in this PR which was very helpful. You can look at the files changed to validate that I did not add anything from the other branch.

**Comment by iRobsc** [comment]
postercard-changes

**Comment by iRobsc** [comment]
The first postercard shows the hover effect

**Comment by willwull** [comment]
Not digging the border tbh

**Comment by iRobsc** [comment]
Removed the border

**Pull request merged**
