### PR TITLE
Fix banner float bug

### PR DESCRIPTION
**Pull request by iRobsc**
fixes: #45

### CODE REVIEW

**Comment by iRobsc** [comment]
There was no way of seeing this bug without implementing the title since there is where the bug occurred in the first place. If I would've known about float being an issue for upcoming elements I wouldn't have used it.

**Comment by pajlilja** [comment]
Oh sorry I didnt know, dont have to be so mad =(

**Comment by iRobsc** [comment]
No problem. Just think about the underlaying causes next time before commenting about what could have been done.

**Comment by willwull** [comment]
Just merge the damn pull request

**Comment by iRobsc** [comment]
@willwull  stay out of this. This is between me and @pajlilja!

**Comment by TNielsen92pro** [comment]
Hey dudes

**Comment by TNielsen92pro** [comment]
whats happening

**Comment by iRobsc** [comment]
Unnecessary comment @TNielsen92pro, this thread should solely be about the pull request and it's content.

**Comment by TNielsen92pro** [comment]
Terribly sorry about the inconvenience

**Pull request merged**
