### PR TITLE
Bugfix detailsinfo

### PR DESCRIPTION
**Pull request by pajlilja**
fixes the bug in issue #94

### CODE REVIEW

**Comment by iRobsc** [comment]
This pull request seems to have the infinity scroll as well, you should remove those commits and only commit the bugfix.

**Comment by pajlilja** [comment]
How?

**Comment by iRobsc** [comment]
Create a new branch and revert the commits you don't want.

**Comment by iRobsc** [comment]
No wait, I don't even think you need to create a new branch.

**Comment by iRobsc** [comment]
Just use the git revert and then use the hash from the commits you want to remove.

**Comment by pajlilja** [comment]
You are speaking in riddles my dear friend

**Comment by iRobsc** [comment]
If you look at commits you will find a hash like: "0d1f8d6" for an example.

**Comment by iRobsc** [comment]
git revert <commit hash>

**Pull request merged**
