### PR TITLE
Implement Sidebar

### LINKED ISSUE #8: Add a component for the sidebar
We need a simple starting component for the sidebar in our project.

### LINKED ISSUE #9: Add button component
Looking at our concept art for the project we have some buttons in the sidebar. We could easily make these buttons a standalone component that can be re-used.

### PR DESCRIPTION
**Pull request by willwull**
This PR builds on top of #21 and adds these features:
* More font weights (see `index.html`), fixes bug where font looked different in Safari compared to Chrome.
* SidebarNavLink component
* Sidebar

fixes #8 
fixes #9

### CODE REVIEW

**Comment by willwull** [comment]
Hold up don't merge yet, adding responsive stuff

**Comment by iRobsc** [comment]
How is it going over there?

**Comment by willwull** [comment]
Not good :((

**Comment by willwull** [comment]
Okay done. Had to move `Router` to `index.js` from `App.js`

**Pull request merged**
